<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

/**
 * App\ProjectFiles
 *
 * @property int $id
 * @property string $name
 * @property int $project_id
 * @property string $path
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Project $project
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ProjectFile newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ProjectFile newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ProjectFile query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ProjectFile whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ProjectFile whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ProjectFile whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ProjectFile wherePath($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ProjectFile whereProjectId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\ProjectFile whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class ProjectFile extends Model
{
    //
    protected $table = 'project_files';
    protected $fillable = ['name', 'path'];
    protected $appends = ['src', 'size'];

    /**
     * @param UploadedFile $uploadedFile
     * @return ProjectFile|Model
     */
    public static function store(UploadedFile $uploadedFile)
    {
        if ($uploadedFile instanceof UploadedFile) {

            $attributes['name'] = $uploadedFile->getClientOriginalName();
            $hash = md5_file($uploadedFile->path());
            $filename = $hash . '.' . $uploadedFile->extension();
            $dir = substr($hash, 0, 2);

            $path = $uploadedFile->storeAs('public/project_files/' . $dir, $filename);

            return self::firstOrCreate(['path' => $path], $attributes);
        }
        throw new \TypeError('Argument must be instance of Illuminate\Http\UploadedFile');
    }

    public function delete()
    {
        Storage::delete($this->path);
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function getSizeAttribute()
    {

        return \Storage::size($this->path);
    }

    public function getSrcAttribute()
    {

        return \Storage::url($this->path);

    }

    public function projects()
    {
        return $this->belongsToMany(Project::class);
    }

}
